# Generated by Django 4.2.23 on 2025-07-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="url",
            field=models.URLField(blank=True, help_text="URL to the problem statement"),
        ),
    ]
