# Generated by Django 4.2.23 on 2025-08-06 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problems", "0003_problem_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="problems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
