# Generated by Django 4.2.23 on 2025-07-24 21:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "avatar",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("github_profile", models.URLField(blank=True)),
                ("linkedin_profile", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "preferred_languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred programming languages",
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="BEGINNER",
                        max_length=20,
                    ),
                ),
                ("problems_solved", models.PositiveIntegerField(default=0)),
                ("total_submissions", models.PositiveIntegerField(default=0)),
                ("successful_submissions", models.PositiveIntegerField(default=0)),
                ("rating", models.PositiveIntegerField(default=1200)),
                ("contests_participated", models.PositiveIntegerField(default=0)),
                (
                    "badges",
                    models.JSONField(
                        blank=True, default=list, help_text="List of earned badges"
                    ),
                ),
                ("experience_points", models.PositiveIntegerField(default=0)),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("LIGHT", "Light"),
                            ("DARK", "Dark"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=10,
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
