# Generated by Django 4.2.23 on 2025-08-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="badges",
        ),
        migrations.RemoveField(
            model_name="user",
            name="experience_points",
        ),
        migrations.AddField(
            model_name="user",
            name="signup_token",
            field=models.CharField(
                default="",
                editable=False,
                help_text="Signup token",
                max_length=64,
                unique=True,
            ),
        ),
    ]
