# Generated by Django 4.2.23 on 2025-08-06 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_badges_remove_user_experience_points_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="signup_token",
        ),
    ]
