# Generated by Django 4.2.23 on 2025-08-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_signup_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signup_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Signup token",
                max_length=500,
                null=True,
            ),
        ),
    ]
