version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: online_judge
      POSTGRES_USER: judge
      POSTGRES_PASSWORD: judgepass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  web:
    build: .
    command: gunicorn online_judge.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://judge:judgepass@db:5432/online_judge
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A online_judge worker --loglevel=info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://judge:judgepass@db:5432/online_judge
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
