# Generated by Django 4.2.23 on 2025-07-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("javascript", "JavaScript"),
                            ("golang", "Go"),
                            ("rust", "Rust"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("accepted", "Accepted"),
                            ("wrong_answer", "Wrong Answer"),
                            ("time_limit", "Time Limit Exceeded"),
                            ("memory_limit", "Memory Limit Exceeded"),
                            ("runtime_error", "Runtime Error"),
                            ("compilation_error", "Compilation Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("memory_used", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [("view_all_solutions", "Can view all solutions")],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("accepted", "Accepted"),
                            ("wrong_answer", "Wrong Answer"),
                            ("time_limit", "Time Limit Exceeded"),
                            ("memory_limit", "Memory Limit Exceeded"),
                            ("runtime_error", "Runtime Error"),
                            ("compilation_error", "Compilation Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("memory_used", models.FloatField(blank=True, null=True)),
                ("output", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="solutions.solution",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.testcase",
                    ),
                ),
            ],
            options={
                "ordering": ["test_case__created_at"],
            },
        ),
    ]
